USE AUG_22

SELECT * FROM CUSTOMER

SELECT * FROM PROD_CAT_INFO 

SELECT * FROM TRANSACTIONS
--------------------------------------------------
-- DATA PREPARATION AND UNDERSTANDING
--------------------------------------------------
--Q1 
SELECT 
(SELECT COUNT(*) FROM CUSTOMER) AS CUST_ROWS,
(SELECT COUNT(*) FROM PROD_CAT_INFO) AS PROD_ROWS,
COUNT(*) FROM TRANSACTIONS AS TRANS_ROWS

--Q2
SELECT COUNT(TRANSACTION_ID) AS TRANSACTION_COUNT
FROM TRANSACTIONS 
WHERE TOTAL_AMT LIKE '-%'

--Q3
SELECT CONVERT(DATE, DOB, 105) AS DOB FROM CUSTOMER 
SELECT CONVERT(DATE, TRAN_DATE, 105) AS TRAN_DATE FROM TRANSACTIONS

--Q4
SELECT 
DATEDIFF(DAY, MIN(CONVERT(DATE, TRAN_DATE, 105)), MAX(CONVERT(DATE,TRAN_DATE, 105)))as DAYS, 
DATEDIFF(MONTH, MIN(CONVERT(DATE, TRAN_DATE, 105)), MAX(CONVERT(DATE,TRAN_DATE, 105))) MONTHS,  
DATEDIFF(YEAR, MIN(CONVERT(DATE, TRAN_DATE, 105)), MAX(CONVERT(DATE,TRAN_DATE, 105))) YEARS
FROM TRANSACTIONS

--Q5
SELECT PROD_CAT
FROM PROD_CAT_INFO
WHERE PROD_SUBCAT = 'DIY'

---------------------------------------------------
-- DATA ANALYSIS 
---------------------------------------------------

--Q1

SELECT TOP 1 STORE_TYPE,
COUNT(TRANSACTION_ID) AS TRANSACTION_COUNT
FROM TRANSACTIONS 
GROUP BY STORE_TYPE
ORDER BY COUNT(TRANSACTION_ID) DESC

--Q2
SELECT GENDER,
COUNT(GENDER) AS GENDER_COUNT
FROM CUSTOMER
GROUP BY GENDER
HAVING GENDER IN ('M','F')

--Q3
SELECT TOP 1 CITY_CODE,
COUNT(CUSTOMER_ID) AS COUSTOMER_COUNT
FROM CUSTOMER
GROUP BY CITY_CODE
ORDER BY COUNT(CUSTOMER_ID) DESC    

--Q4
SELECT COUNT(PROD_SUBCAT) AS SUB_CAT_COUNT
FROM PROD_CAT_INFO
WHERE PROD_CAT ='Books' 

--Q5
SELECT MAX(QTY) AS MAX_PRO_ORDERED
FROM TRANSACTIONS

--Q6
SELECT SUM(TOTAL_AMT) AS NET_TOTAL_REVENUE
FROM TRANSACTIONS AS T1
INNER JOIN PROD_CAT_INFO AS T2
ON T1.PROD_CAT_CODE=T2.PROD_CAT_CODE 
AND PROD_SUB_CAT_CODE = PROD_SUBCAT_CODE
WHERE PROD_CAT IN ('ELECTRONICS' , 'BOOKS')            


-------------------------------------------------------
SELECT * FROM CUSTOMER

SELECT * FROM PROD_CAT_INFO 

SELECT * FROM TRANSACTIONS
--------------------------------------------------------

--Q7 
SELECT CUST_ID,
COUNT(TRANSACTION_ID) AS TRANSACTION_COUNT 
FROM TRANSACTIONS
WHERE TOTAL_AMT NOT LIKE '-%'
GROUP BY CUST_ID
HAVING COUNT(TRANSACTION_ID) > 10

--Q8
SELECT SUM(TOTAL_AMT) AS COMBINED_REVENUE 
FROM TRANSACTIONS AS T1
INNER JOIN PROD_CAT_INFO AS T2
ON T1.PROD_CAT_CODE=T2.PROD_CAT_CODE 
AND PROD_SUBCAT_CODE=PROD_SUB_CAT_CODE 
WHERE PROD_CAT IN ('ELECTRONICS' , 'CLOTHING')
AND STORE_TYPE='FLAGSHIP STORE'

--Q9
SELECT PROD_SUBCAT,
SUM(TOTAL_AMT) AS TOTAL_REVENUE
FROM TRANSACTIONS AS T1
INNER JOIN PROD_CAT_INFO AS T2 
ON T1.PROD_CAT_CODE=T2.PROD_CAT_CODE
AND PROD_SUB_CAT_CODE=PROD_SUBCAT_CODE
INNER JOIN CUSTOMER AS T3
ON CUSTOMER_ID=CUST_ID
WHERE GENDER='M'
AND PROD_CAT='ELECTRONICS'
GROUP BY PROD_SUBCAT

--Q10

SELECT TOP 5 
PROD_SUBCAT, SUM(QTY) AS SALE_QTY,
SUM(CASE WHEN TOTAL_AMT>0 THEN TOTAL_AMT ELSE 0 END)/(SELECT SUM(TOTAL_AMT) FROM TRANSACTIONS)*100 AS SALES_PERCENT,
SUM(CASE WHEN TOTAL_AMT<0 THEN ABS(TOTAL_AMT) ELSE 0 END)/(SELECT SUM(TOTAL_AMT) FROM TRANSACTIONS)*100 AS RETURN_PERCENT
FROM PROD_CAT_INFO AS T1
INNER JOIN TRANSACTIONS AS T2
ON PROD_SUBCAT_CODE=PROD_SUB_CAT_CODE
GROUP BY PROD_SUBCAT
ORDER BY SUM(TOTAL_AMT) DESC


--Q11

SELECT CUST_ID,
SUM(TOTAL_AMT) AS TOTAL_REVENUE
FROM TRANSACTIONS
WHERE CUST_ID IN 
	(
	 SELECT CUSTOMER_ID
	 FROM CUSTOMER
	 WHERE DATEDIFF(YEAR,CONVERT(DATE,DOB,103),GETDATE()) BETWEEN 25 AND 35)
	 AND CONVERT(DATE,TRAN_DATE,103) BETWEEN DATEADD(DAY,-30,(SELECT MAX(CONVERT(DATE,TRAN_DATE,103)) FROM TRANSACTIONS)) 
	 AND (SELECT MAX(CONVERT(DATE,TRAN_DATE,103))FROM TRANSACTIONS
	 )
GROUP BY CUST_ID


--Q12
SELECT TOP 1
PROD_CAT, SUM(TOTAL_AMT)AS MAX_RETURN
FROM TRANSACTIONS AS T1
INNER JOIN PROD_CAT_INFO AS T2 
ON T1.PROD_CAT_CODE = T2.PROD_CAT_CODE 
AND T1.PROD_SUBCAT_CODE = T2.PROD_SUB_CAT_CODE
WHERE TOTAL_AMT < 0 
AND CONVERT(date, TRAN_DATE, 103) BETWEEN DATEADD(MONTH,-3,(SELECT MAX(CONVERT(DATE,TRAN_DATE,103)) FROM TRANSACTIONS)) 
AND (SELECT MAX(CONVERT(DATE,TRAN_DATE,103)) FROM TRANSACTIONS)
GROUP BY PROD_CAT
ORDER BY MAX_RETURN DESC


--Q13
SELECT TOP 1 STORE_TYPE, 
SUM(QTY) AS QUANTITY_SOLD, SUM(TOTAL_AMT) AS SALES_AMOUNT
FROM TRANSACTIONS 
GROUP BY STORE_TYPE 
ORDER BY SUM(QTY) DESC, SUM(TOTAL_AMT) DESC

--Q14

SELECT PROD_CAT,
AVG(TOTAL_AMT) AS PROD_AVG_REVENUE
FROM PROD_CAT_INFO AS T1
INNER JOIN TRANSACTIONS AS T2
ON T1.PROD_CAT_CODE=T2.PROD_CAT_CODE 
GROUP BY PROD_CAT
HAVING AVG(TOTAL_AMT) > (SELECT AVG(TOTAL_AMT) FROM TRANSACTIONS)

--Q15

SELECT PROD_CAT, PROD_SUBCAT, QTY,
AVG(TOTAL_AMT) AS AVG_REVENUE, SUM(TOTAL_AMT) AS TOTAL_REVENUE 
FROM TRANSACTIONS AS T1
INNER JOIN PROD_CAT_INFO AS T2
ON PROD_SUBCAT_CODE=PROD_SUB_CAT_CODE 
WHERE PROD_CAT IN ( 
		SELECT TOP 5 PROD_CAT FROM TRANSACTIONS 
		INNER JOIN PROD_CAT_INFO
		ON PROD_SUB_CAT_CODE=PROD_SUBCAT_CODE
		ORDER BY QTY DESC )
GROUP BY PROD_CAT, PROD_SUBCAT, QTY